In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("datas.csv")

# Text Preprocessing
1. Basic preprocessing
2. Advance

In [3]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

# 1.1 Lower Casing

In [4]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [5]:
df['review']=df['review'].str.lower()

In [6]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# 1.2 : Remove HTML tags

In [7]:
import re

In [8]:
def remove_html(text):
    pattern=re.compile('<.*?>')
    return pattern.sub(r'',text)

In [9]:
df['review']=df['review'].apply(remove_html)

In [10]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

# 1.3 Remove Url

In [11]:
def remove_url(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'',text)

In [12]:
check='''  <h1>Data Science</h1> <p>Data science is an <strong>important field</strong> that combines <em>statistics, programming, and machine learning</em>.</p> <div>Learn more at <a href="https://www.example.com">our website</a> or visit https://www.google.com <a href="https://www.google.com">Google</a>.</div> <ul><li>Python</li><li>Machine Learning</li><li>Data Analysis</li></ul> <br><span>Start learning today!</span>
 '''

In [13]:
check=remove_html(check)

In [14]:
check

'  Data Science Data science is an important field that combines statistics, programming, and machine learning. Learn more at our website or visit https://www.google.com Google. PythonMachine LearningData Analysis Start learning today!\n '

In [15]:
check=remove_url(check)

In [16]:
check

'  Data Science Data science is an important field that combines statistics, programming, and machine learning. Learn more at our website or visit  Google. PythonMachine LearningData Analysis Start learning today!\n '

# 1.4 Remove Punctuation

In [17]:
import string,time

In [18]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [19]:
exclude=string.punctuation

In [20]:
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [21]:
def remove_punc(text):
    for char in exclude:
        text=text.replace(char,'')
    return text

In [22]:
df['review']=df['review'].apply(remove_punc)

In [23]:
df['review'][3]

'basically theres a family where a little boy jake thinks theres a zombie in his closet  his parents are fighting all the timethis movie is slower than a soap opera and suddenly jake decides to become rambo and kill the zombieok first of all when youre going to make a film you must decide if its a thriller or a drama as a drama the movie is watchable parents are divorcing  arguing like in real life and then we have jake with his closet which totally ruins all the film i expected to see a boogeyman similar movie and instead i watched a drama with some meaningless thriller spots3 out of 10 just for the well playing parents  descent dialogs as for the shots with jake just ignore them'

In [24]:
# or there is another way to remove punctuation, and it is way faster than the previous one
def remove_punc2(text):
    return text.translate(str.maketrans('','',exclude))

In [25]:
df['review']=df['review'].apply(remove_punc2)

In [26]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# 1.5 Chat word treatment(treating shorthand word e.g ASAP,Gn,Gm)

In [27]:
!git clone https://github.com/rishabhverma17/sms_slang_translator.git

fatal: destination path 'sms_slang_translator' already exists and is not an empty directory.

In [28]:
import os

os.listdir("sms_slang_translator")

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'LICENSE',
 'Output.jpg',
 'README.md',
 'Screenshot (160).png',
 'Script.py',
 'slang.txt',
 '_config.yml']

In [29]:
with open("sms_slang_translator/slang.txt", "r") as f:
    data = f.read()

print(data)

A3=Anytime, Anywhere, Anyplace
ADIH=Another Day In Hell
AFK=Away From Keyboard
AFAIK=As Far As I Know
ASAP=As Soon As Possible
ASL=Age, Sex, Location
ATK=At The Keyboard
ATM=At The Moment
BAE=Before Anyone Else
BAK=Back At Keyboard
BBL=Be Back Later
BBS=Be Back Soon
BFN=Bye For Now
B4N=Bye For Now
BRB=Be Right Back
BRUH=Bro
BRT=Be Right There
BSAAW=Big Smile And A Wink
BTW=By The Way
BWL=Bursting With Laughter
CSL=Canâ€™t Stop Laughing
CU=See You
CUL8R=See You Later
CYA=See You
DM=Direct Message
FAQ=Frequently Asked Questions
FC=Fingers Crossed
FIMH=Forever In My Heart
FOMO=Fear Of Missing Out
FR=For Real
FWIW=For What It's Worth
FYP=For You Page
FYI=For Your Information
G9=Genius
GAL=Get A Life
GG=Good Game
GMTA=Great Minds Think Alike
GN=Good Night
GOAT=Greatest Of All Time
GR8=Great!
HBD=Happy Birthday
IC=I See
ICQ=I Seek You
IDC=I Donâ€™t Care
IDK=I Don't Know
IFYP=I Feel Your Pain
ILU=I Love You
ILY=I Love You
IMHO=In My Honest/Humble Opinion
IMU=I Miss You
IMO=In My Opinion
IOW=In Other Words
IRL=In Real Life
IYKYK=If You Know, You Know
JK=Just Kidding
KISS=Keep It Simple, Stupid
L=Loss
L8R=Later
LDR=Long Distance Relationship
LMK=Let Me Know
LMAO=Laughing My A** Off
LOL=Laughing Out Loud
LTNS=Long Time No See
M8=Mate
MFW=My Face When
MID=Mediocre
MRW=My Reaction When
MTE=My Thoughts Exactly
NVM=Never Mind
NRN=No Reply Necessary
NPC=Non-Player Character
OIC=Oh I See
OP=Overpowered
PITA=Pain In The A**
POV=Point Of View
PRT=Party
PRW=Parents Are Watching
ROFL=Rolling On The Floor Laughing
ROFLOL=Rolling On The Floor Laughing Out Loud
ROTFLMAO=Rolling On The Floor Laughing My A** Off
RN=Right Now
SK8=Skate
STATS=Your Sex And Age
SUS=Suspicious
TBH=To Be Honest
TFW=That Feeling When
THX=Thank You
TIME=Tears In My Eyes
TLDR=Too Long, Didnâ€™t Read
TNTL=Trying Not To Laugh
TTFN=Ta-Ta For Now!
TTYL=Talk To You Later
U=You
U2=You Too
U4E=Yours For Ever
W=Win
W8=Wait...
WB=Welcome Back
WTF=What The F**k
WTG=Way To Go!
WUF=Where Are You From?
WYD=What You Doing?
WYWH=Wish You Were Here
ZZZ=Sleeping, Bored, Tired

In [30]:
slang_dict = {}

with open("sms_slang_translator/slang.txt", "r") as f:
    for line in f:
        key, value = line.strip().split("=", 1)
        slang_dict[key] = value

In [31]:
slang_dict

{'A3': 'Anytime, Anywhere, Anyplace',
 'ADIH': 'Another Day In Hell',
 'AFK': 'Away From Keyboard',
 'AFAIK': 'As Far As I Know',
 'ASAP': 'As Soon As Possible',
 'ASL': 'Age, Sex, Location',
 'ATK': 'At The Keyboard',
 'ATM': 'At The Moment',
 'BAE': 'Before Anyone Else',
 'BAK': 'Back At Keyboard',
 'BBL': 'Be Back Later',
 'BBS': 'Be Back Soon',
 'BFN': 'Bye For Now',
 'B4N': 'Bye For Now',
 'BRB': 'Be Right Back',
 'BRUH': 'Bro',
 'BRT': 'Be Right There',
 'BSAAW': 'Big Smile And A Wink',
 'BTW': 'By The Way',
 'BWL': 'Bursting With Laughter',
 'CSL': 'Canâ€™t Stop Laughing',
 'CU': 'See You',
 'CUL8R': 'See You Later',
 'CYA': 'See You',
 'DM': 'Direct Message',
 'FAQ': 'Frequently Asked Questions',
 'FC': 'Fingers Crossed',
 'FIMH': 'Forever In My Heart',
 'FOMO': 'Fear Of Missing Out',
 'FR': 'For Real',
 'FWIW': "For What It's Worth",
 'FYP': 'For You Page',
 'FYI': 'For Your Information',
 'G9': 'Genius',
 'GAL': 'Get A Life',
 'GG': 'Good Game',
 'GMTA': 'Great Minds Think Alike',
 'GN': 'Good Night',
 'GOAT': 'Greatest Of All Time',
 'GR8': 'Great!',
 'HBD': 'Happy Birthday',
 'IC': 'I See',
 'ICQ': 'I Seek You',
 'IDC': 'I Donâ€™t Care',
 'IDK': "I Don't Know",
 'IFYP': 'I Feel Your Pain',
 'ILU': 'I Love You',
 'ILY': 'I Love You',
 'IMHO': 'In My Honest/Humble Opinion',
 'IMU': 'I Miss You',
 'IMO': 'In My Opinion',
 'IOW': 'In Other Words',
 'IRL': 'In Real Life',
 'IYKYK': 'If You Know, You Know',
 'JK': 'Just Kidding',
 'KISS': 'Keep It Simple, Stupid',
 'L': 'Loss',
 'L8R': 'Later',
 'LDR': 'Long Distance Relationship',
 'LMK': 'Let Me Know',
 'LMAO': 'Laughing My A** Off',
 'LOL': 'Laughing Out Loud',
 'LTNS': 'Long Time No See',
 'M8': 'Mate',
 'MFW': 'My Face When',
 'MID': 'Mediocre',
 'MRW': 'My Reaction When',
 'MTE': 'My Thoughts Exactly',
 'NVM': 'Never Mind',
 'NRN': 'No Reply Necessary',
 'NPC': 'Non-Player Character',
 'OIC': 'Oh I See',
 'OP': 'Overpowered',
 'PITA': 'Pain In The A**',
 'POV': 'Point Of View',
 'PRT': 'Party',
 'PRW': 'Parents Are Watching',
 'ROFL': 'Rolling On The Floor Laughing',
 'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
 'ROTFLMAO': 'Rolling On The Floor Laughing My A** Off',
 'RN': 'Right Now',
 'SK8': 'Skate',
 'STATS': 'Your Sex And Age',
 'SUS': 'Suspicious',
 'TBH': 'To Be Honest',
 'TFW': 'That Feeling When',
 'THX': 'Thank You',
 'TIME': 'Tears In My Eyes',
 'TLDR': 'Too Long, Didnâ€™t Read',
 'TNTL': 'Trying Not To Laugh',
 'TTFN': 'Ta-Ta For Now!',
 'TTYL': 'Talk To You Later',
 'U': 'You',
 'U2': 'You Too',
 'U4E': 'Yours For Ever',
 'W': 'Win',
 'W8': 'Wait...',
 'WB': 'Welcome Back',
 'WTF': 'What The F**k',
 'WTG': 'Way To Go!',
 'WUF': 'Where Are You From?',
 'WYD': 'What You Doing?',
 'WYWH': 'Wish You Were Here',
 'ZZZ': 'Sleeping, Bored, Tired'}

In [32]:
def chat_conversion(text):
    new_text=[]
    for w in text.split():
        if w.upper() in slang_dict:
            new_text.append(slang_dict[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [33]:
chat_conversion('I WYWH')

'I Wish You Were Here'

In [34]:
chat_conversion('''I am Away From Keyboard right now, please call me ASAP Far As I Know the meeting is starting soon.
By The Way, I will send you the notes later it seams WYD .
Laughing Out Loud, this project is really interesting!''')

'I am Away From Keyboard right now, please call me As Soon As Possible Far As I Know the meeting is starting soon. By The Way, I will send you the notes later it seams What You Doing? . Laughing Out Loud, this project is really interesting!'

# 1.6 Spell Checking

pip install symspellpy

from symspellpy import SymSpell

sy=SymSpell()

sy.load_dictionary("frequency_dictionary_en_82_765.txt",term_index=0,count_index=1)

# (NOTE THAT I FUTURE I HAVE TO LEARN THE SymSpell() RIGHTNOW WILL DO TEXTBLOB)

In [35]:
from textblob import TextBlob

In [36]:
data=""" I am lernng natural langauge processng.
This librarry can corect misspeled words.
The algoritm finds the most likly corrct word
I realy enjoy lernng machin lernng."""

In [37]:
blob=TextBlob(data)
blob.correct().string

' I am leaning natural language processing.\nHis library can correct misspelled words.\nThe algoritm finds the most likely correct word\nI really enjoy leaning machine leaning.'

# 1.7 Remove Stopwords

In [38]:
from nltk.corpus import stopwords

In [39]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [40]:
stopwords.words('arabic')

['إذ',
 'إذا',
 'إذما',
 'إذن',
 'أف',
 'أقل',
 'أكثر',
 'ألا',
 'إلا',
 'التي',
 'الذي',
 'الذين',
 'اللاتي',
 'اللائي',
 'اللتان',
 'اللتيا',
 'اللتين',
 'اللذان',
 'اللذين',
 'اللواتي',
 'إلى',
 'إليك',
 'إليكم',
 'إليكما',
 'إليكن',
 'أم',
 'أما',
 'أما',
 'إما',
 'أن',
 'إن',
 'إنا',
 'أنا',
 'أنت',
 'أنتم',
 'أنتما',
 'أنتن',
 'إنما',
 'إنه',
 'أنى',
 'أنى',
 'آه',
 'آها',
 'أو',
 'أولاء',
 'أولئك',
 'أوه',
 'آي',
 'أي',
 'أيها',
 'إي',
 'أين',
 'أين',
 'أينما',
 'إيه',
 'بخ',
 'بس',
 'بعد',
 'بعض',
 'بك',
 'بكم',
 'بكم',
 'بكما',
 'بكن',
 'بل',
 'بلى',
 'بما',
 'بماذا',
 'بمن',
 'بنا',
 'به',
 'بها',
 'بهم',
 'بهما',
 'بهن',
 'بي',
 'بين',
 'بيد',
 'تلك',
 'تلكم',
 'تلكما',
 'ته',
 'تي',
 'تين',
 'تينك',
 'ثم',
 'ثمة',
 'حاشا',
 'حبذا',
 'حتى',
 'حيث',
 'حيثما',
 'حين',
 'خلا',
 'دون',
 'ذا',
 'ذات',
 'ذاك',
 'ذان',
 'ذانك',
 'ذلك',
 'ذلكم',
 'ذلكما',
 'ذلكن',
 'ذه',
 'ذو',
 'ذوا',
 'ذواتا',
 'ذواتي',
 'ذي',
 'ذين',
 'ذينك',
 'ريث',
 'سوف',
 'سوى',
 'شتان',
 'عدا',
 'عسى',
 'عل',
 'على',
 'عليك',
 'عليه',
 'عما',
 'عن',
 'عند',
 'غير',
 'فإذا',
 'فإن',
 'فلا',
 'فمن',
 'في',
 'فيم',
 'فيما',
 'فيه',
 'فيها',
 'قد',
 'كأن',
 'كأنما',
 'كأي',
 'كأين',
 'كذا',
 'كذلك',
 'كل',
 'كلا',
 'كلاهما',
 'كلتا',
 'كلما',
 'كليكما',
 'كليهما',
 'كم',
 'كم',
 'كما',
 'كي',
 'كيت',
 'كيف',
 'كيفما',
 'لا',
 'لاسيما',
 'لدى',
 'لست',
 'لستم',
 'لستما',
 'لستن',
 'لسن',
 'لسنا',
 'لعل',
 'لك',
 'لكم',
 'لكما',
 'لكن',
 'لكنما',
 'لكي',
 'لكيلا',
 'لم',
 'لما',
 'لن',
 'لنا',
 'له',
 'لها',
 'لهم',
 'لهما',
 'لهن',
 'لو',
 'لولا',
 'لوما',
 'لي',
 'لئن',
 'ليت',
 'ليس',
 'ليسا',
 'ليست',
 'ليستا',
 'ليسوا',
 'ما',
 'ماذا',
 'متى',
 'مذ',
 'مع',
 'مما',
 'ممن',
 'من',
 'منه',
 'منها',
 'منذ',
 'مه',
 'مهما',
 'نحن',
 'نحو',
 'نعم',
 'ها',
 'هاتان',
 'هاته',
 'هاتي',
 'هاتين',
 'هاك',
 'هاهنا',
 'هذا',
 'هذان',
 'هذه',
 'هذي',
 'هذين',
 'هكذا',
 'هل',
 'هلا',
 'هم',
 'هما',
 'هن',
 'هنا',
 'هناك',
 'هنالك',
 'هو',
 'هؤلاء',
 'هي',
 'هيا',
 'هيت',
 'هيهات',
 'والذي',
 'والذين',
 'وإذ',
 'وإذا',
 'وإن',
 'ولا',
 'ولكن',
 'ولو',
 'وما',
 'ومن',
 'وهو',
 'يا',
 'أبٌ',
 'أخٌ',
 'حمٌ',
 'فو',
 'أنتِ',
 'يناير',
 'فبراير',
 'مارس',
 'أبريل',
 'مايو',
 'يونيو',
 'يوليو',
 'أغسطس',
 'سبتمبر',
 'أكتوبر',
 'نوفمبر',
 'ديسمبر',
 'جانفي',
 'فيفري',
 'مارس',
 'أفريل',
 'ماي',
 'جوان',
 'جويلية',
 'أوت',
 'كانون',
 'شباط',
 'آذار',
 'نيسان',
 'أيار',
 'حزيران',
 'تموز',
 'آب',
 'أيلول',
 'تشرين',
 'دولار',
 'دينار',
 'ريال',
 'درهم',
 'ليرة',
 'جنيه',
 'قرش',
 'مليم',
 'فلس',
 'هللة',
 'سنتيم',
 'يورو',
 'ين',
 'يوان',
 'شيكل',
 'واحد',
 'اثنان',
 'ثلاثة',
 'أربعة',
 'خمسة',
 'ستة',
 'سبعة',
 'ثمانية',
 'تسعة',
 'عشرة',
 'أحد',
 'اثنا',
 'اثني',
 'إحدى',
 'ثلاث',
 'أربع',
 'خمس',
 'ست',
 'سبع',
 'ثماني',
 'تسع',
 'عشر',
 'ثمان',
 'سبت',
 'أحد',
 'اثنين',
 'ثلاثاء',
 'أربعاء',
 'خميس',
 'جمعة',
 'أول',
 'ثان',
 'ثاني',
 'ثالث',
 'رابع',
 'خامس',
 'سادس',
 'سابع',
 'ثامن',
 'تاسع',
 'عاشر',
 'حادي',
 'أ',
 'ب',
 'ت',
 'ث',
 'ج',
 'ح',
 'خ',
 'د',
 'ذ',
 'ر',
 'ز',
 'س',
 'ش',
 'ص',
 'ض',
 'ط',
 'ظ',
 'ع',
 'غ',
 'ف',
 'ق',
 'ك',
 'ل',
 'م',
 'ن',
 'ه',
 'و',
 'ي',
 'ء',
 'ى',
 'آ',
 'ؤ',
 'ئ',
 'أ',
 'ة',
 'ألف',
 'باء',
 'تاء',
 'ثاء',
 'جيم',
 'حاء',
 'خاء',
 'دال',
 'ذال',
 'راء',
 'زاي',
 'سين',
 'شين',
 'صاد',
 'ضاد',
 'طاء',
 'ظاء',
 'عين',
 'غين',
 'فاء',
 'قاف',
 'كاف',
 'لام',
 'ميم',
 'نون',
 'هاء',
 'واو',
 'ياء',
 'همزة',
 'ي',
 'نا',
 'ك',
 'كن',
 'ه',
 'إياه',
 'إياها',
 'إياهما',
 'إياهم',
 'إياهن',
 'إياك',
 'إياكما',
 'إياكم',
 'إياك',
 'إياكن',
 'إياي',
 'إيانا',
 'أولالك',
 'تانِ',
 'تانِك',
 'تِه',
 'تِي',
 'تَيْنِ',
 'ثمّ',
 'ثمّة',
 'ذانِ',
 'ذِه',
 'ذِي',
 'ذَيْنِ',
 'هَؤلاء',
 'هَاتانِ',
 'هَاتِه',
 'هَاتِي',
 'هَاتَيْنِ',
 'هَذا',
 'هَذانِ',
 'هَذِه',
 'هَذِي',
 'هَذَيْنِ',
 'الألى',
 'الألاء',
 'أل',
 'أنّى',
 'أيّ',
 'ّأيّان',
 'أنّى',
 'أيّ',
 'ّأيّان',
 'ذيت',
 'كأيّ',
 'كأيّن',
 'بضع',
 'فلان',
 'وا',
 'آمينَ',
 'آهِ',
 'آهٍ',
 'آهاً',
 'أُفٍّ',
 'أُفٍّ',
 'أفٍّ',
 'أمامك',
 'أمامكَ',
 'أوّهْ',
 'إلَيْكَ',
 'إلَيْكَ',
 'إليكَ',
 'إليكنّ',
 'إيهٍ',
 'بخٍ',
 'بسّ',
 'بَسْ',
 'بطآن',
 'بَلْهَ',
 'حاي',
 'حَذارِ',
 'حيَّ',
 'حيَّ',
 'دونك',
 'رويدك',
 'سرعان',
 'شتانَ',
 'شَتَّانَ',
 'صهْ',
 'صهٍ',
 'طاق',
 'طَق',
 'عَدَسْ',
 'كِخ',
 'مكانَك',
 'مكانَك',
 'مكانَك',
 'مكانكم',
 'مكانكما',
 'مكانكنّ',
 'نَخْ',
 'هاكَ',
 'هَجْ',
 'هلم',
 'هيّا',
 'هَيْهات',
 'وا',
 'واهاً',
 'وراءَك',
 'وُشْكَانَ',
 'وَيْ',
 'يفعلان',
 'تفعلان',
 'يفعلون',
 'تفعلون',
 'تفعلين',
 'اتخذ',
 'ألفى',
 'تخذ',
 'ترك',
 'تعلَّم',
 'جعل',
 'حجا',
 'حبيب',
 'خال',
 'حسب',
 'خال',
 'درى',
 'رأى',
 'زعم',
 'صبر',
 'ظنَّ',
 'عدَّ',
 'علم',
 'غادر',
 'ذهب',
 'وجد',
 'ورد',
 'وهب',
 'أسكن',
 'أطعم',
 'أعطى',
 'رزق',
 'زود',
 'سقى',
 'كسا',
 'أخبر',
 'أرى',
 'أعلم',
 'أنبأ',
 'حدَث',
 'خبَّر',
 'نبَّا',
 'أفعل به',
 'ما أفعله',
 'بئس',
 'ساء',
 'طالما',
 'قلما',
 'لات',
 'لكنَّ',
 'ءَ',
 'أجل',
 'إذاً',
 'أمّا',
 'إمّا',
 'إنَّ',
 'أنًّ',
 'أى',
 'إى',
 'أيا',
 'ب',
 'ثمَّ',
 'جلل',
 'جير',
 'رُبَّ',
 'س',
 'علًّ',
 'ف',
 'كأنّ',
 'كلَّا',
 'كى',
 'ل',
 'لات',
 'لعلَّ',
 'لكنَّ',
 'لكنَّ',
 'م',
 'نَّ',
 'هلّا',
 'وا',
 'أل',
 'إلّا',
 'ت',
 'ك',
 'لمّا',
 'ن',
 'ه',
 'و',
 'ا',
 'ي',
 'تجاه',
 'تلقاء',
 'جميع',
 'حسب',
 'سبحان',
 'شبه',
 'لعمر',
 'مثل',
 'معاذ',
 'أبو',
 'أخو',
 'حمو',
 'فو',
 'مئة',
 'مئتان',
 'ثلاثمئة',
 'أربعمئة',
 'خمسمئة',
 'ستمئة',
 'سبعمئة',
 'ثمنمئة',
 'تسعمئة',
 'مائة',
 'ثلاثمائة',
 'أربعمائة',
 'خمسمائة',
 'ستمائة',
 'سبعمائة',
 'ثمانمئة',
 'تسعمائة',
 'عشرون',
 'ثلاثون',
 'اربعون',
 'خمسون',
 'ستون',
 'سبعون',
 'ثمانون',
 'تسعون',
 'عشرين',
 'ثلاثين',
 'اربعين',
 'خمسين',
 'ستين',
 'سبعين',
 'ثمانين',
 'تسعين',
 'بضع',
 'نيف',
 'أجمع',
 'جميع',
 'عامة',
 'عين',
 'نفس',
 'لا سيما',
 'أصلا',
 'أهلا',
 'أيضا',
 'بؤسا',
 'بعدا',
 'بغتة',
 'تعسا',
 'حقا',
 'حمدا',
 'خلافا',
 'خاصة',
 'دواليك',
 'سحقا',
 'سرا',
 'سمعا',
 'صبرا',
 'صدقا',
 'صراحة',
 'طرا',
 'عجبا',
 'عيانا',
 'غالبا',
 'فرادى',
 'فضلا',
 'قاطبة',
 'كثيرا',
 'لبيك',
 'معاذ',
 'أبدا',
 'إزاء',
 'أصلا',
 'الآن',
 'أمد',
 'أمس',
 'آنفا',
 'آناء',
 'أنّى',
 'أول',
 'أيّان',
 'تارة',
 'ثمّ',
 'ثمّة',
 'حقا',
 'صباح',
 'مساء',
 'ضحوة',
 'عوض',
 'غدا',
 'غداة',
 'قطّ',
 'كلّما',
 'لدن',
 'لمّا',
 'مرّة',
 'قبل',
 'خلف',
 'أمام',
 'فوق',
 'تحت',
 'يمين',
 'شمال',
 'ارتدّ',
 'استحال',
 'أصبح',
 'أضحى',
 'آض',
 'أمسى',
 'انقلب',
 'بات',
 'تبدّل',
 'تحوّل',
 'حار',
 'رجع',
 'راح',
 'صار',
 'ظلّ',
 'عاد',
 'غدا',
 'كان',
 'ما انفك',
 'ما برح',
 'مادام',
 'مازال',
 'مافتئ',
 'ابتدأ',
 'أخذ',
 'اخلولق',
 'أقبل',
 'انبرى',
 'أنشأ',
 'أوشك',
 'جعل',
 'حرى',
 'شرع',
 'طفق',
 'علق',
 'قام',
 'كرب',
 'كاد',
 'هبّ']

In [41]:
def remove_stop(text):
    new_txt=[]
    for w in text.split():
        if w in stopwords.words('english'):
            new_txt.append('')
        else:
            new_txt.append(w)
    x=new_txt[:]
    new_txt.clear()
    return " ".join(x)

In [42]:
remove_stop(data)

'I  lernng natural langauge processng. This librarry  corect misspeled words. The algoritm finds   likly corrct word I realy enjoy lernng machin lernng.'

In [43]:
data

' I am lernng natural langauge processng.\nThis librarry can corect misspeled words.\nThe algoritm finds the most likly corrct word\nI realy enjoy lernng machin lernng.'

In [44]:
ndata="my name is inam"

In [45]:
remove_stop(ndata)

' name  inam'

# 1.8 Emoji's handling

In [46]:
import emoji

In [47]:
print(emoji.demojize("The 🥰 Smiling Face with Hearts emoji expresses warm, fuzzy, and tender affection while the 😍") )

The :smiling_face_with_hearts: Smiling Face with Hearts emoji expresses warm, fuzzy, and tender affection while the :smiling_face_with_heart-eyes:

# 2 Tokenization  
1. Word tokenization

Suppose we have:

"I am learning NLP"

Tokenization gives:

["I", "am", "learning", "NLP"]

Each word becomes a token.

In [48]:
# Tokenization using split()
data.split() # word tokenization using space

['I',
 'am',
 'lernng',
 'natural',
 'langauge',
 'processng.',
 'This',
 'librarry',
 'can',
 'corect',
 'misspeled',
 'words.',
 'The',
 'algoritm',
 'finds',
 'the',
 'most',
 'likly',
 'corrct',
 'word',
 'I',
 'realy',
 'enjoy',
 'lernng',
 'machin',
 'lernng.']

In [49]:
data.split('.') # sentence tokenization

[' I am lernng natural langauge processng',
 '\nThis librarry can corect misspeled words',
 '\nThe algoritm finds the most likly corrct word\nI realy enjoy lernng machin lernng',
 '']

In [50]:
# Probelm with split function()
sen1="im going to new delhi!"
sen1.split() # here ! in delhi will be ocnsidered as different from delhi

['im', 'going', 'to', 'new', 'delhi!']

In [51]:
# Or we are going to use the regular expression
sen2=re.findall('[\w]+',sen1)
sen2  # but the problem is if we need the "!" it removes it.

['im', 'going', 'to', 'new', 'delhi']

In [52]:
sen3=""" Yesterday, I went to the market with my friends, and we bought apples, bananas, and oranges. The market was crowded, but everyone seemed happy! We met our teacher there, and she asked, "What are you doing here?" I replied, "We are buying some fruits." After that, we went to a small café,had some coffee, and talked about our NLP project. It was a fun day!
"""

In [53]:
sen3t=re.compile('[.?!,]').split(sen3) 
#This one is usually used when multiple stopping factors are being 
#considered as sentence

In [54]:
sen3t

[' Yesterday',
 ' I went to the market with my friends',
 ' and we bought apples',
 ' bananas',
 ' and oranges',
 ' The market was crowded',
 ' but everyone seemed happy',
 ' We met our teacher there',
 ' and she asked',
 ' "What are you doing here',
 '" I replied',
 ' "We are buying some fruits',
 '" After that',
 ' we went to a small café',
 'had some coffee',
 ' and talked about our NLP project',
 ' It was a fun day',
 '\n']

# 3 NLTK Library

In [55]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [56]:
sen3

' Yesterday, I went to the market with my friends, and we bought apples, bananas, and oranges. The market was crowded, but everyone seemed happy! We met our teacher there, and she asked, "What are you doing here?" I replied, "We are buying some fruits." After that, we went to a small café,had some coffee, and talked about our NLP project. It was a fun day!\n'

In [57]:
word_tokenize(sen3)

['Yesterday',
 ',',
 'I',
 'went',
 'to',
 'the',
 'market',
 'with',
 'my',
 'friends',
 ',',
 'and',
 'we',
 'bought',
 'apples',
 ',',
 'bananas',
 ',',
 'and',
 'oranges',
 '.',
 'The',
 'market',
 'was',
 'crowded',
 ',',
 'but',
 'everyone',
 'seemed',
 'happy',
 '!',
 'We',
 'met',
 'our',
 'teacher',
 'there',
 ',',
 'and',
 'she',
 'asked',
 ',',
 '``',
 'What',
 'are',
 'you',
 'doing',
 'here',
 '?',
 "''",
 'I',
 'replied',
 ',',
 '``',
 'We',
 'are',
 'buying',
 'some',
 'fruits',
 '.',
 "''",
 'After',
 'that',
 ',',
 'we',
 'went',
 'to',
 'a',
 'small',
 'café',
 ',',
 'had',
 'some',
 'coffee',
 ',',
 'and',
 'talked',
 'about',
 'our',
 'NLP',
 'project',
 '.',
 'It',
 'was',
 'a',
 'fun',
 'day',
 '!']

In [58]:
sent_tokenize(sen3)

[' Yesterday, I went to the market with my friends, and we bought apples, bananas, and oranges.',
 'The market was crowded, but everyone seemed happy!',
 'We met our teacher there, and she asked, "What are you doing here?"',
 'I replied, "We are buying some fruits."',
 'After that, we went to a small café,had some coffee, and talked about our NLP project.',
 'It was a fun day!']

In [59]:
sen4="I'm doing P.hD in A.i"

In [60]:
word_tokenize(sen4)

['I', "'m", 'doing', 'P.hD', 'in', 'A.i']

#### *spaCy is another library mainly used for tokenization. Also, in the future, we may use this more often for complex tokenization, as it works better.*

# 4 Stemming:-> 
```Stemming in NLP means cutting a word down to its basic/root-like form by removing prefixes or suffixes.  ```

In [61]:
# Stemming is mainly used is information retrival system(for example google search engine).
# For stemming we will use the PorterStemmer() from nltk library especially for english.

In [62]:
from nltk.stem.porter import PorterStemmer

In [63]:
sen3

' Yesterday, I went to the market with my friends, and we bought apples, bananas, and oranges. The market was crowded, but everyone seemed happy! We met our teacher there, and she asked, "What are you doing here?" I replied, "We are buying some fruits." After that, we went to a small café,had some coffee, and talked about our NLP project. It was a fun day!\n'

In [64]:
ps=PorterStemmer()

In [69]:
def stem(text):
    return ' '.join([ps.stem(w) for w in text.split()])

In [70]:
stem(sen3)

'yesterday, i went to the market with my friends, and we bought apples, bananas, and oranges. the market wa crowded, but everyon seem happy! we met our teacher there, and she asked, "what are you do here?" i replied, "we are buy some fruits." after that, we went to a small café,had some coffee, and talk about our nlp project. it wa a fun day!'

# 5 LEMMATIZATION

```STEMMING word → chop letters → approximate root```  


```LEMMATIZATION word → understand linguistic form → dictionary lemma```

In [71]:
from nltk.stem import WordNetLemmatizer

In [72]:
wl=WordNetLemmatizer()

In [73]:
sen3

' Yesterday, I went to the market with my friends, and we bought apples, bananas, and oranges. The market was crowded, but everyone seemed happy! We met our teacher there, and she asked, "What are you doing here?" I replied, "We are buying some fruits." After that, we went to a small café,had some coffee, and talked about our NLP project. It was a fun day!\n'

In [74]:
punct='?.!:;,'

In [77]:
sen_word=word_tokenize(sen3)
sen_word

['Yesterday',
 ',',
 'I',
 'went',
 'to',
 'the',
 'market',
 'with',
 'my',
 'friends',
 ',',
 'and',
 'we',
 'bought',
 'apples',
 ',',
 'bananas',
 ',',
 'and',
 'oranges',
 '.',
 'The',
 'market',
 'was',
 'crowded',
 ',',
 'but',
 'everyone',
 'seemed',
 'happy',
 '!',
 'We',
 'met',
 'our',
 'teacher',
 'there',
 ',',
 'and',
 'she',
 'asked',
 ',',
 '``',
 'What',
 'are',
 'you',
 'doing',
 'here',
 '?',
 "''",
 'I',
 'replied',
 ',',
 '``',
 'We',
 'are',
 'buying',
 'some',
 'fruits',
 '.',
 "''",
 'After',
 'that',
 ',',
 'we',
 'went',
 'to',
 'a',
 'small',
 'café',
 ',',
 'had',
 'some',
 'coffee',
 ',',
 'and',
 'talked',
 'about',
 'our',
 'NLP',
 'project',
 '.',
 'It',
 'was',
 'a',
 'fun',
 'day',
 '!']

In [89]:
for w in sen_word:
    if w in punct:
        sen_word.remove(w)
# print(sen_word)
print("{0:20}{1:20}".format("WORDS","LEMMA"))
for w in sen_word:
    print("{0:20}{1:20}".format(w,wl.lemmatize(w,pos="v")))

WORDS               LEMMA
Yesterday           Yesterday
I                   I
went                go
to                  to
the                 the
market              market
with                with
my                  my
friends             friends
and                 and
we                  we
bought              buy
apples              apples
bananas             bananas
and                 and
oranges             oranges
The                 The
market              market
was                 be
crowded             crowd
but                 but
everyone            everyone
seemed              seem
happy               happy
We                  We
met                 meet
our                 our
teacher             teacher
there               there
and                 and
she                 she
asked               ask
``                  ``
What                What
are                 be
you                 you
doing               do
here                here
''                  ''
I                   I
replied             reply
``                  ``
We                  We
are                 be
buying              buy
some                some
fruits              fruit
''                  ''
After               After
that                that
we                  we
went                go
to                  to
a                   a
small               small
café                café
had                 have
some                some
coffee              coffee
and                 and
talked              talk
about               about
our                 our
NLP                 NLP
project             project
It                  It
was                 be
a                   a
fun                 fun
day                 day

# Assignment  
1. Create a dataset.(Multi Class Classification)
2. Text Preprocessing.
Dataset-> Movie dataset(columns-> movie name,description, genre)

# Use TMBD API use that a make an algorihtm